services:
  backoffice.image.ImageRepository:
   class: ../../../../contexts/backoffice/image/infrastructure/persistence/InMemoryImageRepository

  backoffice.image.ImageSaver:
    class: ../../../../contexts/backoffice/image/application/save/ImageSaver
    arguments: ['@backoffice.image.ImageRepository']
    
  backoffice.image.SaveImageCommandHandler:
    class: ../../../../contexts/backoffice/image/application/save/SaveImageCommandHandler
    arguments: ['@backoffice.image.ImageSaver']
    tags:
      - {name: commandHandler}

  apps.backoffice.controllers.StatusHealhCheckGetController:
    class: ../../controllers/health-check/StatusHealhCheckGetController
    arguments: []

  shared.CommandHandlers:
    class: ../../../../contexts/shared/domain/bus/command/CommandHandlers
    arguments: ['!tagged commandHandler'] 

  shared.CommandBus:
    class: ../../../../contexts/shared/infrastructure/bus/command/InMemoryCommandBus
    arguments: ['@shared.CommandHandlers']

  shared.EventToSubscribers:
    class: ../../../../contexts/shared/domain/bus/event/EventToSubscribers
    arguments: []

  shared.EventBus:
    class: ../../../../contexts/shared/infrastructure/bus/event/InMemorySyncEventBus
    arguments: ['@shared.EventToSubscribers']

  apps.backoffice.controllers.SubmitImagePutController:
    class: ../../controllers/submit-image/SubmitImagePutController
    arguments: ['@shared.CommandBus']