name: Node CI

on: [push]

jobs:
  setup:
    name: Setup Node Environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

  clean:
    name: Clean Build.Remove any possible prod directory
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Remove build. Clean action.
        run: npm run clean

  lint:
    name: Lint Project
    runs-on: ubuntu-latest
    needs: clean
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm i
      - name: Lint project
        run: npm run lint:src

  unit-test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Run unit tests
        run: npm run test:unit

  integration-test:
    name: Run Integrations Tests
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Run unit tests
        run: npm run test:integration

  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: integration-test
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build:prod


